apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-php
  template:
    metadata:
      labels:
        app: apache-php
    spec:
      hostNetwork: true
      containers:
        - name: apache-php
          image: custom-apache-php:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: apache-php
  ports:
    - port: 80
      targetPort: 80
  clusterIP: None